{% set name = "yews" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: .
  #git_url: https://github.com/lijunzh/yews.git
  #git_tag: {{ version }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - pytorch >=1.0.0

test:
  imports:
    - yews

about:
  home: https://github.com/lijunzh/yews
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'Yews: Your Earthquake Waveform Solutions.'

extra:
  recipe-maintainers:
    - lijunzh